### ISSUE TITLE
the “归” word is wrong

### ISSUE THREAD

**Issue by hingbong** [ButTaiwan/genyog-font#1]
the “归” word is wrong,hope you will fix it.

**Comment by ButTaiwan** [comment]
這應該思源KR版本的字樣。
簡體字的部分不是主要支援項目，會放在比較後期的版本修改。
如果方便的話是否能夠協助有哪些簡體字需要改的，再一併修改。

ps.
思源JP/KR版本字樣不知道為什麼長這樣，Unihan database也沒有JP/KR Source...
或許是個可以提給思源本家的issue。

**Comment by hingbong** [comment]
再报一个，“名”字结构不对，也可以等上报的多了，你再修改吧，谢谢了

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/29570380-e7e11fe6-8788-11e7-91fe-6d8ecf4019d8.png)

謝謝回報！

同樣，這也是因為選擇KR版本的結果。暫定改用TW版本，以與其他夕字統一。
（同樣等下一個大改版時）

**Comment by hingbong** [comment]
![default](https://user-images.githubusercontent.com/26398240/29814696-df939568-8c73-11e7-95ef-31237cc954f0.JPG)
有个小统计

**Comment by ButTaiwan** [comment]
上表部份文字已在 Ver. 1.300 修正。
![image](https://user-images.githubusercontent.com/5418570/45954057-89f76f80-c03e-11e8-8521-c4ca5ceca468.png)
