### ISSUE TITLE
「鍺」字系列多一點

### ISSUE THREAD

**Issue by Binjohn** [ButTaiwan/genyog-font#10]
其他像「著賭」字也有這個情形，但這好像算舊字體，不確定源樣黑體會怎麼選？

![鍺](https://user-images.githubusercontent.com/43265566/55345741-4006af00-54e3-11e9-968a-bc121dd2c044.png)

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/77812593-48d19700-70dd-11ea-862a-83e1a5f12a80.png)

**Comment by Binjohn** [comment]
了解，謝謝。我以為已經改了這麼多年，這可能會被當作錯字了？
在我看來，跟「步」和「歩」的感覺差不多，寫考卷會被老師打錯。

**Comment by ButTaiwan** [comment]
最簡單的判斷方式...
去日星鑄字行看一下鉛字是哪個寫法，原則上就是選哪個寫法。
我沒打算考古，就是以鉛字～照相排版初期常見的寫法為準。

**Comment by aikahiiragi** [comment]
> 好吧，我是覺得已經改了這麼多年，這可能要算是錯字了。 在我看來，跟「步」和「歩」的感覺差不多。

可不可以不要胡亂把傳統有字理的正確字形誣衊成「錯字」？
「者頭」和「老頭」自古就是不同的部件，區分起來是有好處的，比較符合字源的。
敎育部從俗而已，不等於本來有字理的正確字形要受冤枉，要背負失實的罵名！

**Comment by Binjohn** [comment]
> > 好吧，我是覺得已經改了這麼多年，這可能要算是錯字了。 在我看來，跟「步」和「歩」的感覺差不多。

原句用「可能」，說明我並不懂如何判定，該回覆旨在「發問」是否為錯字，感謝But大的回覆與解釋。

> 可不可以不要胡亂把傳統有字理的正確字形誣衊成「錯字」？ 「者頭」和「老頭」自古就是不同的部件，區分起來是有好處的，比較符合字源的。 敎育部從俗而已，不等於本來有字理的正確字形要受冤枉，要背負失實的罵名！

我把源樣字體用在教材上，起初是因為發現字體跟課本寫的不一樣，所以來發問。
個人對字體沒有研究，各位的回應我都要查資料才看得懂，還請各位專家鞭小力一點。

回過神來發現有3人對我的評論按了「爛」，很抱歉讓各位不舒服。

**Comment by aikahiiragi** [comment]
> > > 好吧，我是覺得已經改了這麼多年，這可能要算是錯字了。 在我看來，跟「步」和「歩」的感覺差不多。
> 
> 原句用「可能」，說明我並不懂如何判定，該回覆旨在「發問」是否為錯字，感謝But大的回覆與解釋。
> 

抱歉看到「……了。」這種寫法，理解不到是發問。如果是「……嗎？」的話，會明白是發問。

> > 可不可以不要胡亂把傳統有字理的正確字形誣衊成「錯字」？ 「者頭」和「老頭」自古就是不同的部件，區分起來是有好處的，比較符合字源的。 敎育部從俗而已，不等於本來有字理的正確字形要受冤枉，要背負失實的罵名！
> 
> 我把源樣字體用在教材上，起初是因為發現字體跟課本寫的不一樣，所以來發問。 個人對字體沒有研究，各位的回應我都要查資料才看得懂，還請各位專家鞭小力一點。

敎材要看是哪種，如果是台灣的，而且一定要遵守敎育部標準的，就用「思源黑體TW」。

> 回過神來發現有3人對我的評論按了「爛」，很抱歉讓各位不舒服。

抱歉其中一個是我。因爲一些具有字理的、傳統來說是正確的寫法，在敎育部扶正俗寫後，被冤枉、被指責或被懷疑是錯字的事情發生了太多次了。

**Comment by Binjohn** [comment]
> 抱歉看到「……了。」這種寫法，理解不到是發問。如果是「……嗎？」的話，會明白是發問。

我自己現在讀起來也覺得不妥，已修改。
當初可能是因為承接最初「不確定……？」的提問，所以我就這樣寫了。

> 敎材要看是哪種，如果是台灣的，而且一定要遵守敎育部標準的，就用「思源黑體TW」。

主要是因為源樣系列有修正行高，所以用在Word比較方便。
用思源黑體的話我至今都覺得處理起來很痛苦，所以很排斥。

> 抱歉其中一個是我。因爲一些具有字理的、傳統來說是正確的寫法，在敎育部扶正俗寫後，被冤枉、被指責或被懷疑是錯字的事情發生了太多次了。

完全理解，是我的問題。學到了，感謝！

**Comment by aikahiiragi** [comment]
> > 抱歉看到「……了。」這種寫法，理解不到是發問。如果是「……嗎？」的話，會明白是發問。
> 
> 我自己現在讀起來也覺得不妥，已修改。 當初可能是因為承接最初「不確定……？」的提問，所以我就這樣寫了。
> 
> > 敎材要看是哪種，如果是台灣的，而且一定要遵守敎育部標準的，就用「思源黑體TW」。
> 
> 主要是因為源樣系列有修正行高，所以用在Word比較方便。 用思源黑體的話我至今都覺得處理起來很痛苦，所以很排斥。
> 
> > 抱歉其中一個是我。因爲一些具有字理的、傳統來說是正確的寫法，在敎育部扶正俗寫後，被冤枉、被指責或被懷疑是錯字的事情發生了太多次了。
> 
> 完全理解，是我的問題。學到了，感謝！

感謝修改和抱歉。其實是整個漢字教育的問題。
扶正俗寫（不當成錯誤，學生寫了不打交叉不扣分）有實用性，我明白，
但反而把本來傳統上正確的被當成錯誤，就本末倒置，
漢字教育本來有責任要教學生兩種（多種）寫法都是對的，但實際上很少這樣教。
然後大家不懂，就把默書以外的寫法說成是錯字，這情況遇得多就心累了。
（我是從 #30 過來的，那帖更心累，「丹青」的「青」字被冤枉得更多次。）

**Comment by Binjohn** [comment]
> 感謝修改和抱歉。其實是整個漢字教育的問題。 扶正俗寫（不當成錯誤，學生寫了不打交叉不扣分）有實用性，我明白， 但反而把本來傳統上正確的被當成錯誤，就本末倒置， 漢字教育本來有責任要教學生兩種（多種）寫法都是對的，但實際上很少這樣教。 然後大家不懂，就把默書以外的寫法說成是錯字，這情況遇得多就心累了。 （我是從 #30 過來的，那帖更心累，「丹青」的「青」字被冤枉得更多次。）

讀了您的文章，真是一篇好文，感謝您願意花時間詳細解說。
點開文章之後，我很快就會意「青」字底下的「丹」其實就源自於丹青。
這真的是很好的例子！原來教育部標準字體也帶來了一些問題呢。
