### ISSUE TITLE
希望從思源黑體 v2 匯入新字形

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ButTaiwan/genyog-font#11]
去年釋出的思源黑體 v2 修改了多個字元，2.001 甚至加入了表示令和年號的字，希望源樣黑體也能更進。下面是官方的説明：
![SourceHanSansReadMe1](https://user-images.githubusercontent.com/10364351/56864819-91a53b00-69b6-11e9-8130-8f7bbc2610ce.png)
![SourceHanSansReadMe2](https://user-images.githubusercontent.com/10364351/56864838-c87b5100-69b6-11e9-979e-17aa0a49190a.png)

**Comment by ButTaiwan** [comment]
Ver 1.500 仍採用思源黑體V1為基底，不過已納入部分 V2 字符。
![image](https://user-images.githubusercontent.com/5418570/79038962-570cd080-7c10-11ea-9edf-01366428693b.png)
