### ISSUE TITLE
《南》字還沒有修正

### ISSUE THREAD

**Issue by CoolMarvel43** [ButTaiwan/genyog-font#12]
源樣黑體 v1.500
![Annotation 2020-04-11 184520](https://user-images.githubusercontent.com/10541683/79042231-613ac900-7c28-11ea-9919-2a4ce792681e.png)

思源黑體 v2.001
![Annotation 2020-04-11 184608](https://user-images.githubusercontent.com/10541683/79042232-61d35f80-7c28-11ea-8f06-affa4cfe287c.png)

上面的十字bug也包括源石黑體和源泉黑體。

**Comment by ButTaiwan** [comment]
日星鉛字。或許我反而比較打算去改明體......

![image](https://user-images.githubusercontent.com/5418570/79042307-3309b900-7c29-11ea-8c4c-c852711ab95e.png)

**Comment by ButTaiwan** [comment]
已改用 V2 製作。
