### ISSUE TITLE
建議從思源黑體V2中加入簡體的「𰻝」（ㄅㄧㄤˊ，U+30EDD）

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyog-font#16]
如題，建議可以在源樣系列中加入思源黑體V2的簡體「𰻝」（ㄅㄧㄤˊ，U+30EDD）字。

P.S.目前源泉圓體M以上的字重在處理繁體的ㄅㄧㄤˊ時，筆畫會變得有點奇怪
![01](https://user-images.githubusercontent.com/42777336/79321345-c569cf80-7f3d-11ea-8b0d-a59ec99bd79a.png)

**Comment by ButTaiwan** [comment]
V2 已完整收錄思源 V2 所有漢字。
