### ISSUE TITLE
建議從思源黑體V2中加入新的化學元素用字

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyog-font#17]
如題，目前思源黑體V2已有，但源樣系列尚未加入的化學元素用字有：
鿫：9FEB
鿬：9FEC
鿔：9FD4
鿭：9FED
𫟷：2B7F7

建議大大可以將這些字加入源樣系列。

**Comment by Marcus98T** [comment]
我本來要想增加[全部的v2字形](https://github.com/adobe-fonts/source-han-sans/issues/180)，但是我現在沒時間找到思源黑體的 Character ID Sequence (CID)......

**Comment by ButTaiwan** [comment]
已改用 V2 製作。
