### ISSUE TITLE
ttc轉換爲ttf後，hinting信息丟失

### ISSUE THREAD

**Issue by DarthRL** [ButTaiwan/genyog-font#18]
otc2otf轉得的ttf顯示網頁小字時，鋸齒毛刺明顯，但用系統字體的ttc版本渲染就很清晰。在Medium字重以上尤其明顯。使用1.3版本的ttf無此問題。

**Comment by ButTaiwan** [comment]
在技術上來說，ttf 與 otf 規格最大的差異就是 hinting，完全不相容。
otf hinting 採用半自動 hinting 概念。對整個字型設定主要的數據（overshoot、stem width等等），再針對特定文字指定座標的相對關係，而主要的調校工作都交給 render engine。
ttf hinting 則是通常是全手動概念。要對每個字、每個尺寸，人工指定外框要怎麼挪移。甚至還要對 GrayScale、ClearType、DirectWrite 等各種不同 render engine 模式分別調整不同數據。
所以將 otf 轉換成 ttf，基本上為的就是 Office 軟體相容性（例如 PowerPoint 能不能嵌入字型、Word容易正常匯出PDF等等），但 hinting 一定是全放棄。技術上也幾乎不可能重新 hinting。
（實務上，除了系統字型如微軟正黑體、Meiryo外，幾乎沒有業者會對 CJK ttf 進行 hinting，因為要針對各種不同 render engine、對每個字的每個大小逐一調整顯示效果，比造一套字的工程還高好幾倍。事實上，發明這種 ttf hinting 的 Apple 公司本身，自從 Mac 採用 retina 螢幕後，根本已經忽略 ttf hinting 資訊不處理了。）

所以，本專案是不可能進行 hinting 的。

但是，1.301版為止有另外加入 gasp table，建議系統盡量啟用 ClearType 等機制去做平滑處理。1.500 版確實忘記加上 gasp table 了。（因為換了4K螢幕後自己不容易發現.... 汗）。
下一次有微調改版時會補上 gasp table，但是顯示效果還是要看 OS、瀏覽器的設計。

**Comment by DarthRL** [comment]
感謝解惑，受益匪淺，大大辛苦了！

**Comment by KrasnayaPloshchad** [comment]
如果確有必要進行 hingting 的話不妨試試 [ttfautohint](https://freetype.org/ttfautohint/index.html)，這個工具基於 FreeType 開發，用來簡化 TTF 字形檔的 hingting 工作。

**Comment by ButTaiwan** [comment]
記得之前的版本有嘗試 ttfautohint 過，但效果不是很好（本來 ttfautohint 就不是針對 CJK 設計）。
歡迎實驗調校出理想的 ttfautohint 參數分享，後續版本是可以檢討XD

**Comment by RodertHaung** [comment]
更紗黑體:https://github.com/be5invis/Sarasa-Gothic
這個字體的特點就是有ttf hinting資料。

**Comment by ButTaiwan** [comment]
> 更紗黑體:https://github.com/be5invis/Sarasa-Gothic
> 這個字體的特點就是有ttf hinting資料。

畢竟該專案的參數頂多只適合源樣，源石、源泉...之類的外框大概不會適合。
我想hinting還是讓有興趣嘗試的人fork出去實驗好了。
