### ISSUE TITLE
希望能增加JP版本

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyog-font#2]
首先感謝But大大耗時製作了這套字體，非常的好用。

不過這字體卻無日文版本，不便於中日文混排的情況。

雖有原版思源黑體與思源真黑體等修改版可使用，但這些字體並無行高之類的修正，導致其在某些軟體與源樣黑體混排時產生行高不一致的問題。

因此仍希望But大大能夠製作源樣黑體的日文版本。

**Comment by ButTaiwan** [comment]
放出來了。

**Comment by chlbc** [comment]
趕緊來用用看～感謝But大大！！
