### ISSUE TITLE
逐字的部件不一問題

### ISSUE THREAD

**Issue by luke871016** [ButTaiwan/genyog-font#20]
https://imgur.com/a/wSBbrMa
似乎是思源韓國版的問題，「逐」這個字的部件造型長的跟其他類似文字部件不一樣
像是「遂、象、豕」等等的
導致使用源樣系列打出「逐家好」這句每天都在講的超高頻率使用打招呼詞彙時就會注意到部件不統一。
思源的台坂在這方面就沒有這問題，煩請But ko大大考慮在接下來的更新中修正這個字

**Comment by ButTaiwan** [comment]
根據一字不兩捺原則，下面辶已經是捺結尾了，上方的部件會刻意避開改捺為點。
這是書法與漢字設計常態。思源黑體TW也是點。

![image](https://user-images.githubusercontent.com/5418570/114361212-73877400-9ba8-11eb-990a-8e6c99a87351.png)
