### ISSUE TITLE
部分漢字的 "多" 部，"掰" 與JP的 "栓" 需要改字形

### ISSUE THREAD

**Issue by CoolMarvel43** [ButTaiwan/genyog-font#21]
"夠" 要改成TW字形，以多部統一。
<img width="136" alt="Screenshot 2020-09-27 at 18 25 29" src="https://user-images.githubusercontent.com/10541683/94386456-4b8b7280-017a-11eb-8073-3c850e080399.png">

還有 "陊拸跢翗郺袲痑" and "謻嗲橠"
<img width="730" alt="Screenshot 2020-09-28 at 11 27 31" src="https://user-images.githubusercontent.com/10541683/94387815-d883fb00-017d-11eb-8d05-926072fea4d1.png">
<img width="370" alt="Screenshot 2020-09-28 at 15 45 38" src="https://user-images.githubusercontent.com/10541683/94404879-46dab480-01a2-11eb-95ea-3bc9496c4d2e.png">

下面思源黑體TW的 legend:
綠色是可以換的。
藍色是因為還有新字形部，但是多部可以統一。
橙色是有台灣標準字形，除非要用 font editor 改，還是不用改。(姼茤熪)
紅色是思源黑體TW的 mapping 問題。

---

"栓" 是日文常用漢字，所以右上部應該是人，不是入。這也包括明體。
<img width="293" alt="Screenshot 2020-09-27 at 18 26 55" src="https://user-images.githubusercontent.com/10541683/94386687-df5d3e80-017a-11eb-89dc-8c7ac0592c4d.png">

---

"掰" 也需要改成TW字形。

<img width="156" alt="Screenshot 2020-09-30 at 16 59 36" src="https://user-images.githubusercontent.com/10541683/94665288-85a57180-033e-11eb-80aa-e413976a3f45.png">

**Comment by CoolMarvel43** [comment]
"兎" 也需要改成JP字形。**UPDATE:** 不要改"冤"和"免"。
<img width="252" alt="Screenshot 2020-10-02 at 14 47 43" src="https://user-images.githubusercontent.com/10541683/94895548-40a84900-04be-11eb-9b39-6af2fc3cc033.png">

"U+60EA 惪" 應該使用 "U+60B3 悳"。

**Comment by ButTaiwan** [comment]
> "掰" 也需要改成TW字形。

我覺得左邊的手寫成撇的版本比較好看耶....
（要查一下鉛字）
