### ISSUE TITLE
糨字顯示為⿰米强而不是⿰米強

### ISSUE THREAD

**Issue by duyuang** [ButTaiwan/genyog-font#22]
如題，[源石黑體](https://github.com/ButTaiwan/genseki-font)與[源泉圓體](https://github.com/ButTaiwan/gensen-font)也有同樣的情況，而[源樣明體](https://github.com/ButTaiwan/genyo-font)等沒有，請問是刻意為之還是程序自動生成時遺漏了？

**Comment by ButTaiwan** [comment]
看來應該是思源黑體/思源宋體原始的KR對應就不同。
（思源黑體、思源宋體的異體收錄情況其實很多字都不盡相同）

**Comment by duyuang** [comment]
> 原來是這樣，感謝：）

**Comment by duyuang** [comment]
原來是這樣，感謝：）

**Comment by ButTaiwan** [comment]
2.000 應該有修掉這個字了。
