### ISSUE TITLE
「研、併、教」等字的字型問題

### ISSUE THREAD

**Issue by q120144178** [ButTaiwan/genyog-font#25]
您好：
在這想詢問一下，之前下載的源樣黑體 v1.3標題幾個字的寫法皆採舊字型，
不知道為何更新到 v1.5就改變了，如圖：
![image](https://user-images.githubusercontent.com/21129193/120911937-b6a02800-c6bd-11eb-9b38-9c76c703774e.png)
此外，如果現在要下載源樣黑體先前的版本，是否有提供，我只有看到 v1.5版以後的，謝謝～

**Comment by ButTaiwan** [comment]
單純 v1.5 政策調整。這幾個字在 Unicode 都有並收，這樣的字形比較容易打出不同的字形。

之前的版本請自己翻 GitHub 的 History。

**Comment by CoolMarvel43** [comment]
我建議下次可以使用 OpenType 的 Glyph Variants。目前TW版本沒有這種的 Glyph Variants。
<img width="324" alt="Screenshot 2021-08-20 at 22 58 52" src="https://user-images.githubusercontent.com/10541683/130253026-3733b8cc-afed-423b-be3f-78623582a08d.png">

**Comment by ButTaiwan** [comment]
> 我建議下次可以使用 OpenType 的 Glyph Variants。目前TW版本沒有這種的 Glyph Variants。

glyph variants 對大多用戶來說其實不太實用....
這系列就是預設為一般非 Adobe 軟體使用者，主要是用在 Word 與 PowerPoint 為主的用戶製作的。
所以才全部 ttf 化。

**Comment by aikahiiragi** [comment]
可是輸入法難以打出下面三個真正的舊字形，
我現在也只能打出「研、併、教」這三個字碼。
這三個字碼變成了新字形，令我使用時感到苦惱。
