### ISSUE TITLE
「辵」的部件字形不統一？

### ISSUE THREAD

**Issue by whyjz** [ButTaiwan/genyog-font#26]
測試台語輸入時發現的，「逃」、「𨑨」、「迌」三字有不同長相的偏旁，不知是刻意為之還是有其他因素？

![辵部](https://user-images.githubusercontent.com/19339926/138167504-84df42ea-be17-4348-b01a-eab3608ec14a.png)
(源樣黑體 L)

**Comment by ButTaiwan** [comment]
除了原來思源黑體未收的百餘字之外，凡是思源黑體原先已有的字，都會優先使用原來的字符。

（專案頁有說明）

> Note: 本專案並沒有造新的字符，所有字符都是來自思源黑體本身。所以KR版本未收錄的罕用字或簡化字，仍然會是TW、CN風格

採用的優先順序是 KR > TW > (JP >) CN 

逃字來自 KR，𨑨字因為韓文缺字而來自 TW（香港外字HKSCS有收）、迌字來自 CN（因為 GB18030 收錄了完整Unicode 3.0漢字，其他字集缺的字最後多半會 fallback 到 CN）。


確實這樣部件會很不統一，但請理解每要人工修改一個字，就必須同時改多個字重。
如果要去人工調整這種問題，這會是2萬字乘上多個字重的超級大工程。實際上超過個人可處理的量。

**Comment by whyjz** [comment]
感謝 @ButTaiwan 的詳盡說明！從 Readme 可以大致猜出原因，但我還真沒想到𨑨和迌是來自不同字集。了解問題來源後我就可以在我的專案頁說明了 :) 對我來說修正字形部件並不是必須要處理的項目，因此再交給您決定是否要關閉此 issue。
