### ISSUE TITLE
リクエスト：日本語用旧字体フォント

### ISSUE THREAD

**Issue by ghost** [ButTaiwan/genyog-font#27]
現在ある日本語用と繁体字中国語用とは別に、伝統的な旧字体の日本語用フォントを作っていただけないでしょうか。
漢字の字形は繁体字中国語とほぼ同じ(細部は要調査)、句読点の位置は日本語用と同じです。

**Comment by ghost** [comment]
想定される使用法
- 伝統的な旧字体を好む人が、日常的に使用する
- 日本語話者が漢文用のフォントとして使う。
- 新字体で書かれたウェブサイトで部分的に旧字体で表記する場合(固有名詞など)に、CSSで指定する。
  - 日本語版ウィキペディアには[「Template:旧字体」というテンプレートがあります](https://ja.wikipedia.org/wiki/Template:%E6%97%A7%E5%AD%97%E4%BD%93)。このテンプレートは、記事で旧字体を併記する際に使用するのですが(使用例は[こちら](https://ja.wikipedia.org/wiki/%E7%89%B9%E5%88%A5:%E3%83%AA%E3%83%B3%E3%82%AF%E5%85%83/Template:%E6%97%A7%E5%AD%97%E4%BD%93))、旧字体用のフォントとして游明朝が指定されています。游明朝は常用漢字のしんにょうが1点である、しめすへんが「ネ」の形であるなど、とても旧字体用とは言えません。旧字体用のフォントが必要とされているにも関わらず、適切なフォントが存在しないことが伺えます。

**Comment by ghost** [comment]
軽く調査してみましたが、覆・告・夢が現在のGenYoGothic TWと異なります。
字形を選定する上で参考にできそうな資料として、[こちら](https://github.com/ichitenfont/inheritedglyphs/blob/master/component_of_recom_inherited_glyphs-1.35.pdf)があります。
繁体字中国語用の資料ですが、書いてあることは概ね日本の旧字体にも当てはまります。

**Comment by ButTaiwan** [comment]
日本語フォントの旧字体というのは、厳密な定義があります。
「常用漢字表」に掲載される括弧付き文字です。
たとえば掲→揭・経→經は旧字体だが、戸→戶・之繞、しめすへんなどは旧字体関係ではありません。
常用漢字表に掲載されている旧字体だけ、人名などに使えるので、法律上の意味があります。

![image](https://user-images.githubusercontent.com/5418570/143254010-3fbe9890-41ea-44e8-ab61-e3c3d7b03a16.png)

故に游明朝（だけでなくほぼすべての日本語商用フォント）の旧字体は厳密に「常用漢字表」の定義で作られています。


もちろん「旧字旧かなファン」としては、二点之繞などに統一された字形で読みたいだろう。
ただ既存の源ノ明朝などの trad（旧字体）フィーチャー情報が使えない限り、一つ一つ選定しなければならないため、仕事量が大変です。
選定しづらい文字もかなりあります。（たとえば却の旧字体は却のままか、TWのように卻にするか）
