### ISSUE TITLE
「蘊 U+860A」異體字 「藴 U+85F4」似乎缺失unicode

### ISSUE THREAD

**Issue by huihuieer** [ButTaiwan/genyog-font#29]
![image](https://github.com/ButTaiwan/genyog-font/assets/129865036/17b45f6b-4029-4ea5-a19d-23fd9b242dd7)

**Comment by ButTaiwan** [comment]
如同其他青、為等文字的處理方式，目前版本兩者都統一為「蘊」寫法。
