### ISSUE TITLE
其中一個字「鎮」字打錯了

### ISSUE THREAD

**Issue by kochiyachika** [ButTaiwan/genyog-font#3]
「鎮」字會顯示為「鎖」字（台版才會出現該問題）

**Comment by ButTaiwan** [comment]
這個問題太大，今天會修正。

**Comment by ButTaiwan** [comment]
TW版已更新為版本 Ver. 1.301。
Windows重新安裝覆蓋即可，Mac重新安裝同名字型要完全重開機才會生效。

![image](https://user-images.githubusercontent.com/5418570/45953901-0f2e5480-c03e-11e8-89f3-ede05420e72b.png)

**Comment by chlbc** [comment]
TW版的版本號沒有改到，目前依然寫Ver. 1.300

**Comment by ButTaiwan** [comment]
已確認問題。
不過因為不影響使用，下次有實質更新再異動吧。
