### ISSUE TITLE
[青] 字旁與教育部辭典寫法不符

### ISSUE THREAD

**Issue by ddddo86** [ButTaiwan/genyog-font#30]
![螢幕擷取畫面 2023-08-17 232752](https://github.com/ButTaiwan/genyog-font/assets/107015163/ea851ae4-e691-4a53-aa8a-245733f2392c)
如上圖，青字旁的文字目前是錯誤的
使用平台: microsoft office 365

**Comment by aikahiiragi** [comment]
希望樓主明白，敎育部辭典不是唯一的標準，與敎育部辭典寫法不符，不等於「是錯誤的」。有些寫法甚至比敎育部寫法更正確、更符合學理。

與敎育部不符的原因有很多，當中有些字，只不過是敎育部沒有最優先考慮字源字理，選了比較違背字源字理的寫法來做「標準」，對公眾又缺乏漢字構造和六書的正確敎育。結果反而使有些字的原來寫法（較具備字理、較貼合字源的寫法），被不知道當中學問的人誤當成「錯字」，無辜地背上「錯字」之名。但其實那些寫法比敎育部選擇的字形更正確、更傳統、更具備字理、更能追溯或反映字源。要這種更正確的字形，無辜背上「錯誤」之標籤，實在非常冤枉。

而「青」字正是這樣的字，反而是敎育部選了俗寫而已。「青」字的六書原理，[香港中文大學的文字聲韻學網站](https://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=%E9%9D%92)說得很清楚。它的上方由「屮」或「生」發展而來，都代表草。下方可以是「丹」或「井」。「丹」字會意（「丹青」都是可作顏料之物，「丹」是類屬，草色顏料出來的顏色就是青），「井」字形聲。

到了今天楷書，下方「円」就是「丹」，只是作為偏旁筆畫有少許不同而已（就像「水」的下方偏旁作「氺」、左旁偏旁作「氵」一樣）。《康熙字典》說得很清楚：
![image](https://github.com/ButTaiwan/genyog-font/assets/37748071/e85585f3-4c0c-4714-8731-445520678cb4)
（轉引自[維基百科：國字標準字體](https://zh.wikipedia.org/wiki/%E5%9C%8B%E5%AD%97%E6%A8%99%E6%BA%96%E5%AD%97%E9%AB%94)）

反而寫作「月」，在六書裏沒有辦法可以解釋，只能說它是「訛變」出來的字形，即是說本來是從錯寫、誤寫而來的。

因此，如樓主圖中的「青」字寫法，才是更正確、更符合字源、更具備字理的字形。敎育部的寫法，只能說是把俗寫「扶正」。這俗寫也很普及，不視作錯字，視作合格的寫法，OK。不過，更正確的寫法，不應該被說成是「錯誤」。這樣反過來，就是顛倒了。

而不同字型有不同製作宗旨和作用。這字型本來就不是要依照敎育部寫法，而是讓使用者可以在正體（繁體）中文裏選用一些傳統的寫法。如果改掉了，反而令原來的使用者失去這選擇的權利。如果你想什麼字都只依敎育部標準，大可用回「思源黑體TW」。可是如果不是做小學敎材，我認為比敎育部標準更正確的寫法，其實更值得和更需要大家保存和活用，否則大家都不知道這些字形更正確，它們漸漸會被取代、被消失，到那時候才回頭發現就為時已晚了。

到了結尾，鄭重希望閣下明白我所說的，不要看到與敎育部不一樣就說是「錯誤」，有些不符合敎育部的寫法可能是更正確的。

**Comment by ButTaiwan** [comment]
<img width="633" alt="image" src="https://github.com/ButTaiwan/genyog-font/assets/5418570/afc6055c-c3b3-442e-b671-b2fea21d1604">

此為專案基本初衷。
