### ISSUE TITLE
为 Homebrew 贡献源樣黑體：关于 2.100 版本文件变更及多语种支持的疑问

### ISSUE THREAD

**Issue by singularitti** [ButTaiwan/genyog-font#34]
作者您好，

我是 [Homebrew](https://brew.sh/) 的贡献者，负责将“源樣黑體”推送到 macOS 的包管理器 [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/font/font-g/font-genyogothic.rb) 中。Homebrew 可以方便地将二进制字体文件分发到 macOS 用户群体中。

我注意到字体从 2.000 版本升级到 2.100 版本时，`GenKiGothic2-N.ttc` 文件被移除了。请问确实如此吗？

另外，从 2.000 版本开始似乎添加了多语种支持。由于我是业余时间维护该项目，且非字体行业专家，所以不能逐一查证。为了方便维护，我希望提交尽量少的修改到 Homebrew 中。因此，请问是否有一个包含尽可能多语种和字形的单一发行包？具体来说，[GenKiGothic2-ttc.zip](https://github.com/ButTaiwan/genyog-font/releases/download/v2.100/GenKiGothic2-ttc.zip) 文件是否足够？

我们更倾向于提交 OTF 格式的字体到 Homebrew 中。请问是否有包含所有语种的 OTF 文件可供下载？

我将 [贡献指南](https://github.com/Homebrew/homebrew-linux-fonts/blob/6875ad445d91a68f12371f6a9fb406d007a05b02/CONTRIBUTING.md?plain=1#L107-L117) 翻译成中文并贴在下面，供您参考：

> ## 每个 Cask 中包含多个字体
> 
> 在一个发行包中通常会提供多种字体样式或系列。当字体被一起分发时，它们应该一起安装。每个 Cask 应对应一个二进制发行包，而不必仅限于单一的字体样式。
> 
> 同样地，同一字体的不同字重可能会在不同的二进制文件中分发。我们遵循相同的规则：每个发行包对应一个独立的 Cask。
> 
> 当后端的 Ruby 代码变得更为复杂时，这一限制可能会有所变化。
> 
> ### 多种字体格式
> 
> 如果一个发行包中提供了同一字体的多种文件格式，例如同时提供 TTF 和 OTF 文件，只需包含其中一种格式。OTF 优先于 TTF。

感谢您的帮助！

**Comment by ButTaiwan** [comment]
> 我注意到字体从 2.000 版本升级到 2.100 版本时，`GenKiGothic2-N.ttc` 文件被移除了。请问确实如此吗？

是的。因為R跟N粗細差異細微，在GenYo的otf還有hinting的情況下可能分得出來，但加工後版本由於都沒有hinting資訊，區別更不明顯，就剔除掉減少容量了。

> 
> 另外，从 2.000 版本开始似乎添加了多语种支持。由于我是业余时间维护该项目，且非字体行业专家，所以不能逐一查证。为了方便维护，我希望提交尽量少的修改到 Homebrew 中。因此，请问是否有一个包含尽可能多语种和字形的单一发行包？具体来说，[GenKiGothic2-ttc.zip](https://github.com/ButTaiwan/genyog-font/releases/download/v2.100/GenKiGothic2-ttc.zip) 文件是否足够？
> 我们更倾向于提交 OTF 格式的字体到 Homebrew 中。请问是否有包含所有语种的 OTF 文件可供下载？

ttc 版本就是所有語種的合併（TW、TC、JP、PJP 四合一），只佔用一個字型的空間。
一般情況下都建議使用 ttc 版本即可，除非是特定軟體不支援 ttc 時，才需要使用單語種的 otf 版本。
比照1.500版只配送 *-ttc.zip 即可，謝謝！

**Comment by singularitti** [comment]
多谢!
