### ISSUE TITLE
JP Normal 的「八屋根」部件沒更新到

### ISSUE THREAD

**Issue by lapomme** [ButTaiwan/genyog-font#4]
![image](https://user-images.githubusercontent.com/27000939/45990430-3e4cc200-c04e-11e8-8c91-1b607a30c967.png)

**Comment by ButTaiwan** [comment]
咦，JP版好像檔案仍然是1.200。
晚上再查一下。

PS. 我有在考慮要不要直接刪掉Normal好了，反正實際上與Regular的粗細差異在預期用途下幾乎沒差異。

**Comment by lapomme** [comment]
Normal用於低解析度螢幕比較清晰一些

**Comment by huangdonghai** [comment]
> 
> 
> 咦，JP版好像檔案仍然是1.200。
> 晚上再查一下。
> 
> PS. 我有在考慮要不要直接刪掉Normal好了，反正實際上與Regular的粗細差異在預期用途下幾乎沒差異。

在视网膜屏幕下，normal和regular差异很大

**Comment by ButTaiwan** [comment]
Normal (DemiLight) 與 Regular 太過接近，再考慮從 OpenType 轉 TrueType 的四捨五入誤差，已經沒意義了。
