### ISSUE TITLE
一些TW字形可能需要改變 (比如: 最, 即, 明, 朝, 的, etc.)

### ISSUE THREAD

**Issue by CoolMarvel43** [ButTaiwan/genyog-font#5]
我還以為有些字形還沒有改變，所以提出來。右邊的隱藏字形都在思源黑體/明體字體裡面。

![glyph change](https://user-images.githubusercontent.com/10541683/46363608-1391e780-c6a6-11e8-8c27-fdf379b97706.png)
![default](https://user-images.githubusercontent.com/10541683/46365883-48a13880-c6ac-11e8-9238-14fd60e5b4c1.png)

請參考此鏈接: [https://github.com/MoneMizuno/Genne-Gothic](https://github.com/MoneMizuno/Genne-Gothic)和[這個文件](https://github.com/MoneMizuno/Genne-Gothic/blob/master/Other/Other/CMap%E6%9B%BF%E6%8F%9B%E8%A1%A8_Genne%20Gothic_1.004.ods)。

這些建議包括你所有的字形。原諒我重複issues。多謝。

**Comment by ButTaiwan** [comment]
整併至此 https://github.com/ButTaiwan/genyo-font/issues/9
