### ISSUE TITLE
「肏」字

### ISSUE THREAD

**Issue by lapomme** [ButTaiwan/genyog-font#6]
（包括源石黑體、源泉圓體）
![default](https://user-images.githubusercontent.com/27000939/47008934-435ed780-d109-11e8-84bb-1aaaf3e09f7e.png)

思源黑體TW版本的「肏」字形比較適合（入部件）

**Comment by ButTaiwan** [comment]
fixed in Ver 1.500
![image](https://user-images.githubusercontent.com/5418570/79038984-7572cc00-7c10-11ea-90f8-547b2856df3a.png)
