### ISSUE TITLE
原樣黑體是不是少了一個自重？

### ISSUE THREAD

**Issue by huangdonghai** [ButTaiwan/genyog-font#7]
DemiLight這個字重沒有

**Comment by ButTaiwan** [comment]
Normal (DemiLight) 與 Regular 太過接近，再考慮從 OpenType 轉 TrueType 的四捨五入誤差，已經沒意義了。

**Comment by Provissy** [comment]
用於Chrome時, Regular稍顯粗而Light又過細, 希望能補充DemiLight. 另許多Unicode編碼相異的字被統一寫為舊印刷字形, 合二Unicode字符為一(如「為」與「即」), 雖為有意而為之, 望可以單獨發行對應Unicode之版本備用.

**Comment by ButTaiwan** [comment]
> 用於Chrome時, Regular稍顯粗而Light又過細, 希望能補充DemiLight.

從 OpenType 轉 TrueType 後，會有四捨五入誤差，而且 hinting 資訊會全丟失。
難以得到預期的效果，這兩個字重的差別已經沒有意義了。

> 另許多Unicode編碼相異的字被統一寫為舊印刷字形, 合二Unicode字符為一(如「為」與「即」), 雖為有意而為之, 望可以單獨發行對應Unicode之版本備用.

目前整個 Project 字型檔大小總合已經達到 1GB。
不太可能為了這個理由多做一個版本，得去維護 2GB 的字型檔。

**Comment by KrasnayaPloshchad** [comment]
> 目前整個 Project 字型檔大小總合已經達到 1GB。
> 不太可能為了這個理由多做一個版本，得去維護 2GB 的字型檔。

如果思源黑體支援了 font variation，那麼這應該會方便得多。

**Comment by ButTaiwan** [comment]
> 如果思源黑體支援了 font variation，那麼這應該會方便得多。

目前這些專案使用到的第三方工具還不太能支援 variable fonts。
就算思源有公開 variable fonts，可能我也沒辦法順利後製是真的。

另外，像是源雲明體那個概念的字型，應該是沒辦法做成 variable fonts。
（因為筆畫交接處也都柔和掉了，並不是單純的筆劃組合）
