### ISSUE TITLE
⾃⽣⼤⾼⼯⾳⼀ 缺字問題

### ISSUE THREAD

**Issue by xup61069** [ButTaiwan/genyog-font#8]
似乎是康熙部首字碼，好像在某些裝置上會轉換出這種字
問題字：⾃⽣⼤⾼⼯⾳⼀
一般字：自生大高工音一

**Comment by ButTaiwan** [comment]
基本上是刻意拿掉康熙部首字碼的。
就是希望比較容易去檢查文章不要誤用康熙部首字碼。

**Comment by xup61069** [comment]
希望可以在那些字上做個記號，這樣可以提供一般閱讀，同時保持檢查誤用的功能，不知道可不可行？

**Comment by ButTaiwan** [comment]
> 希望可以在那些字上做個記號，這樣可以提供一般閱讀，同時保持檢查誤用的功能，不知道可不可行？

思源本來的做法是讓康熙部首文字跟一般漢字共用一個字符，如果要加上記號的話，變成不能共用字符，要做成新字符了。這樣字型檔還得多出200多個字。
